stages:
  - lint
  - build
  - push

variables:
  DOCKER_IMAGE: "l4mbada/rebrain"
  DOCKER_TAG: "nginx-latest"

lint:
  stage: lint
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - docker run --rm -i hadolint/hadolint < Dockerfile

build:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  
push:
  stage: push
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main