---
- name: Add nginx repository gpg key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add nginx repository into sources list
  apt_repository:
    repo: deb https://nginx.org/packages/mainline/ubuntu/ focal nginx
    state: present

- name: Install nginx
  apt:
    update_cache: true
    cache_valid_time: 3600
    name: nginx
    state: present