version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - voting
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`voting.158.160.61.36.nip.io`) || Host(`voting.158.160.44.115.nip.io`) || Host(`voting.158.160.52.47.nip.io`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      replicas: 3
    networks:
      - voting-network

  voting:
    image: voting:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./.env.dist:/var/www/html/.env
    ports:
      - 9000:9000
    depends_on:
      - mysql
    networks:
      - voting-network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: voting
      MYSQL_USER: voting
      MYSQL_PASSWORD: voting
      MYSQL_ROOT_PASSWORD: voting
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - voting-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
    networks:
      - voting-network

volumes:
  mysql-data:

networks:
  voting-network:
    driver: overlay
    external: true