---
- name: Add nginx repository gpg key
  ansible.builtin.apt_key:
   url: https://nginx.org/keys/nginx_signing.key
   state: present
- name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:nginx/stable
    
- name: Install nginx
  ansible.builtin.apt:
   update_cache: true
   cache_valid_time: 3600
   name: nginx
   state: present
