---
- name: Install Let's Encrypt Certbot client
  when: inventory_hostname in groups['load_balancer']
  ansible.builtin.apt:
    pkg: certbot
    state: present
    cache_valid_time: 600

- name: Install certbot plugin 'nginx' on webserver
  when: inventory_hostname in groups['load_balancer']
  ansible.builtin.apt:
    pkg: python3-certbot-nginx
    state: present
    cache_valid_time: 600

- name: Register Certbot
  when: inventory_hostname in groups['load_balancer']
  shell: |
        certbot -n register --agree-tos --email l4mbada@yandex.ru
        touch /etc/letsencrypt/.registered
  args:
        creates: /etc/letsencrypt/.registered

- name: 'Get certificate'
  when: inventory_hostname in groups['load_balancer']
  command: 'certbot --nginx certonly -d {{ server_name_1 }}'
  args:
      creates: '/etc/letsencrypt/live/{{ server_name_1 }}'

- name: Delete "default.conf"
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/conf.d/default.conf

- name: Recreate load_balancer.conf with ssl
  when: inventory_hostname in groups['load_balancer']
  vars:
    ssl: true
  ansible.builtin.template:
    src: 'loadbalancer.conf.j2'
    dest: /etc/nginx/conf.d/{{ server_name_1 }}.conf
    mode: "755"
  
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
