---
- name: Create a path if it does not exist
  ansible.builtin.file:
    path: /etc/letsencrypt/live/{{ server_name }}
    state: directory
    mode: '0755'

- name: Copy cert into nginx server
  ansible.builtin.copy:
    decrypt: true
    src: ../secrets/{{ item }}
    dest: /etc/letsencrypt/live/{{ server_name }}/{{ item }}
    mode: '755'
  loop: 
    - fullchain.pem
    - privkey.pem

- name: Kill nginx process
  ansible.builtin.shell:
   cmd: sudo pkill -f nginx
  ignore_errors: true

- name: Start nginx
  systemd:
    name: nginx
    state: started

- name: Recreate virtualhost with ssl
  vars: 
    ssl: true
  template:
    src: 'virtualhosts.conf.j2'
    dest: /etc/nginx/conf.d/vhost.conf
  notify: Reload nginx