---
- name: Nginx
  hosts: do_vps
  roles: 
   - role: 'nginx'

- name: Certificate
  hosts: do_vps
  roles:
   - role: 'certificate'

- name: Ensure public SSH key is exist
  hosts: localhost
  tasks:
    - name: Get stats of a file
      ansible.builtin.stat:
       path: "/home/root/.ssh/id_ed25519"
      register: key_path

    - name: Create a path if it does not exist
      when: key_path.stat.path is not defined
      block:
      - name: Create a directory if it does not exist
        ansible.builtin.file:
          path: /home/root/.ssh
          state: directory
          mode: '0755'

      - name: Generate SSH key
        community.crypto.openssh_keypair:
          path: /home/root/.ssh/id_ed25519
          type: ed25519
          owner: root
          group: root
        register: key_result
    
    - name: Encrypt variable
      ansible.builtin.shell:
       cmd: ansible-vault encrypt_string --vault-password-file ../secrets/secret_pass '{{ server_name }}' --name 'server_name' --output ../group_vars/all
                 
- name: Set authorized key  
  hosts: do_vps
  tasks:
  - name: Set authorized key 
    authorized_key:
      user: root
      state: present
      # key: public_ssh_key
      key: "{{ lookup('file', '/home/root/.ssh/id_ed25519.pub') }}"

  